package sec02.exam02;

public class TryCatchFinallyRuntimeExceptionExample {

	public static void main(String[] args) {

		String data1 = null;
		String data2 = null;
		
		try {
			data1 = args[0];
			data2 = args[2];
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("실행 매개값의 수가 부족합니다.");
		}
		
	}

}
